## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'moke'  

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_moke' #to modify
description = 'Kerr Magneto Optics experiments'

author = 'Sebastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq_plugins_daqmx',
 'pymodaq_plugins_andor']
