#this is the configuration file of PyMoDAQ
[macro]


[micro]

    [micro.current]
    device_ao = 'cDAQ1Mod4'
    device_ai = 'cDAQ1Mod1'
    channel_ao = 'ao0'
    channel_ai = 'ai0'
    resistor = 1  # resistor value in ohm to read current from voltage measurement

    [micro.led]
    device_di = 'cDAQ1Mod5'
    port_di = 'port0'
    line_di = 'line0'
    device_ao = 'cDAQ1Mod3'
    channels_ao = ['ao2', 'ao3', 'ao1', 'ao0']
    changedetectionevent_device = 'cDAQ1'

    [micro.actuation]
    absolute_current_values = [0.1, 0.5, 2.0]
    relative_value = 0.15